sudo: false

os:
  - linux
  # - windows

language: node_js

node_js:
  - "10"
  - "12"
  - "node"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
  - export PATH=$HOME/.yarn/bin:$PATH

script:
  yarn test

cache:
  yarn: true
